book_publishing/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views
from books import views as book_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.MyLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('books.urls')),
    path(r'^$', book_views.book),
]

books/urls.py
from django.urls import path
from . import views
from .views import (
    BookUpdateView,
)
app_name='books'

urlpatterns = [
    path('', views.home, name='home'),
    path('book', views.book, name='book'),
    path('author', views.author, name='author'),
    path('publisher', views.publisher, name='publisher'),
    path('query', views.query, name='query'),
    path('search-book', views.search_books, name='search-book'),
    path('search-author', views.search_author, name='search-author'),
    path('search-publisher', views.search_publisher, name='search-publisher'),
    path('<str:state>/insert/', views.insert, name='insert'),
    path('<str:state>/<str:m_pk>/edit', views.edit, name='edit'),
    path('<str:state>/<str:m_pk>/delete_data/', views.delete, name='delete_data'),
]

books/models.py
from django.db import models

class Publisher(models.Model):
    name = models.CharField(primary_key=True, max_length=200)  # Field name made lowercase.
    address = models.TextField(blank=True, null=True)  # Field name made lowercase.
    phone = models.CharField(max_length=20)  # Field name made lowercase.

    def __str__(self):
        return self.name

    class Meta:
        managed = True
        db_table = 'publisher'

class Author(models.Model):
    author_name = models.CharField(primary_key=True, max_length=200)  # Field name made lowercase.
    date_of_birth = models.DateField()  # Field name made lowercase.

    works_for = models.ManyToManyField(Publisher, related_name='authors')

    def __str__(self):
        return self.author_name
    class Meta:
        managed = True
        db_table = 'author'


class Book(models.Model):
    isbn = models.CharField(primary_key=True, max_length=15)  # Field name made lowercase.
    title = models.CharField(max_length=200)  # Field name made lowercase.
    published_date = models.DateField()  # Field name made lowercase.
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)  # Field name made lowercase.

    written = models.ManyToManyField(Author, related_name='books')

    def __str__(self):
        return f'{self.isbn} {self.title}'
    class Meta:
        managed = True
        db_table = 'book'

books/forms.py
from django import forms

from .models import Book, Author, Publisher
import datetime

class BookForm(forms.ModelForm):
    published_date = forms.DateField(initial=datetime.date.today)
    class Meta:
        model = Book
        fields = '__all__'


class AuthorForm(forms.ModelForm):
    date_of_birth = forms.DateField(initial=datetime.date.today)
    class Meta:
        model = Author
        fields = '__all__'


class PublisherForm(forms.ModelForm):
    class Meta:
        model = Publisher
        fields = '__all__'

books/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import BookForm, AuthorForm, PublisherForm
from books.models import Book, Publisher, Author
from django.contrib import messages
from django.contrib.auth.decorators import login_required
import MySQLdb



from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)

def home(request):
    context = {
        'state': 'home',
    }
    return render(request, 'books/book_home.html', context)

def book(request):
    form = BookForm()
    book_list = Book.objects.all()
    books = _get_object_paginator(request, book_list)
    fields_book = Book._meta.get_fields()
    # print(fields_book)
    context = {
        'books': books,
        'fields': fields_book,
        'state': 'book',
        'form': form
    }
    return render(request, 'books/book_list.html', context)


def insert(request, state):
    if request.method != 'POST':
        return redirect(f'/{state}')

    if state == "book":
        form = BookForm(request.POST)
    elif state == "author":
        form = AuthorForm(request.POST)
    elif state == "publisher":
        form = PublisherForm(request.POST)
    
    if form.is_valid():
        form.save()
        messages.success(request, 'Insert Success')
    else:
        messages.warning(request, 'Insert Error')
    return redirect(f'/{state}')
class BookUpdateView(UpdateView):
    model = Book
    fields = '__all__'

    def form_valid(self, form):
        clean = form.cleaned_data 
        context = {}        
        self.object = context.save(clean) 
        return super(BookUpdateView, self).form_valid(form)


def _get_object_paginator(request, obj_list):
    page = request.GET.get('page', 1)

    paginator = Paginator(obj_list, 5)
    try:
        return paginator.page(page)
    except PageNotAnInteger:
        return paginator.page(1)
    except EmptyPage:
        return paginator.page(paginator.num_pages)

def search_books (request):
    # a = Book.written.objects.all()
    global book_qs
    form = BookForm()
    if request.method == 'POST':
        book_qs = Book.objects.all().order_by('title')
        book_name = request.POST['book_name']
        publisher_name = request.POST['publisher_name']
        year = request.POST['year']
        if(book_name != '' and book_name != None):
            # print(f'Hey i want to see book name: {book_name}')
            book_qs = book_qs.filter(title__istartswith = book_name)
        if(publisher_name != '' and publisher_name != None):
            # print(f'I want to know publisher name: {publisher_name}')
            book_qs = book_qs.filter(publisher__name__istartswith = publisher_name)
        if(year != '' and year != None):
            # print(f'I want to know year: {year}')
            try:
                book_qs = book_qs.filter(published_date__year = year)
            except:
                pass
        book_pageobj = _get_object_paginator(request, book_qs)
        context = {
            'books':book_pageobj, 
            'state': 'book',
            'form': form
        }
        return  render(request,'books/book_list.html', context)
    else:
        book_pageobj = _get_object_paginator(request, book_qs)
        context = {
            'books':book_pageobj, 
            'state': 'book',
            'form': form    
        }
        return  render(request,'books/book_list.html',context)        

def author(request):
    form = AuthorForm()
    author_list = Author.objects.all()
    authors = _get_object_paginator(request, author_list)
    context = {
        'authors': authors,
        'state': 'author',
        'form': form
    }
    # print(context)
    return render(request, 'books/author_list.html', context)

def search_author (request):
    global author_keyword
    form = AuthorForm()
    if request.method == 'POST':
        keyword_a = request.POST['name']
        author_keyword = Author.objects.filter(author_name__istartswith = keyword_a)
        authors_filter = _get_object_paginator(request, author_keyword)
        context = {
            'authors':authors_filter,
            'state': 'author',
            'form': form
        }
    else:
        authors_filter = _get_object_paginator(request, author_keyword)
        context = {
            'authors':authors_filter, 
            'state': 'author',
            'form': form    
        }
    return  render(request,'books/author_list.html',context)


def publisher(request):
    form = PublisherForm()
    publisher_list = Publisher.objects.all()
    publishers = _get_object_paginator(request, publisher_list)
    context = {
        'publishers': publishers,
        'state': 'publisher',
        'form': form
    }
    return render(request, 'books/publisher_list.html', context)

def search_publisher (request):
    global publisher_keyword
    form = PublisherForm()
    if request.method == 'POST':
        keyword_a = request.POST['name']
        publisher_keyword = Publisher.objects.filter(name__istartswith = keyword_a)
        publishers_filter = _get_object_paginator(request, publisher_keyword)
        context = {
            'publishers':publishers_filter,
            'state': 'publisher',
            'form': form
        }
    else:
        publishers_filter = _get_object_paginator(request, publisher_keyword)
        context = {
            'publishers':publishers_filter, 
            'state': 'publisher',
            'form': form    
        }
    return  render(request,'books/publisher_list.html',context)

def delete(request,state,m_pk):
    if state=="book":
        data = Book.objects.get(isbn=m_pk)
    elif state=="author":
        data = Author.objects.get(author_name=m_pk)
    elif state=="publisher":   
        data = Publisher.objects.get(name=m_pk)
    data.delete()
    messages.success(request, f'Delete {state.capitalize()} Success')
    return HttpResponseRedirect(reverse(f'books:{state}'))

def edit(request,state,m_pk):
    if state=="book":
        if request.method == 'POST':
            try :
                data = Book.objects.get(isbn=m_pk)
                data.isbn = request.POST['isbn']
                data.title = request.POST['title']
                data.published_date = request.POST['published_date']
                data.publisher= Publisher.objects.get(name=request.POST['publisher'])
                data.save()
                messages.success(request, 'Edit Success')
            except:
                messages.warning(request, 'Edit Error')

        fields_book = Book._meta.get_fields()[:3]
        d_book = Book.objects.get(isbn = m_pk )
        d_book_list = Book.objects.values_list().get(isbn = m_pk )
        p_pk = Publisher.objects.all()
        a_pk = Author.objects.all()
        mylist = zip(fields_book,d_book_list)
        context = {"state":"book","mylist":mylist,"pk":m_pk,"d_book":d_book.publisher.name,"publisher_name":p_pk,"a_name":a_pk}
                
    elif state=="author":
        if request.method == 'POST':
            try :
                data = Author.objects.get(author_name=m_pk)
                data.author_name = request.POST['author_name']
                data.date_of_birth = request.POST['date_of_birth']
                data.save()
                messages.success(request, 'Edit Success')
            except:
                messages.warning(request, 'Edit Error')
        p_pk = Publisher.objects.all()
        d_author_list = Author.objects.values_list().get(author_name = m_pk )
        d_author = Author.objects.get(author_name = m_pk )
        fields_author = Author._meta.get_fields()[1:3]
        mylist = zip(fields_author,d_author_list)
        context = {"state":"author","mylist":mylist,"pk":m_pk,"publisher_name":p_pk}

    elif state=="publisher":
        if request.method == 'POST':
            try :
                data = Publisher.objects.get(name=m_pk) 
                data.name = request.POST['name']
                data.address=request.POST['address']
                data.phone=request.POST['phone']
                data.save()
                messages.success(request, 'Edit Success')
            except:
                messages.warning(request, 'Edit Error')
        d_publisher = Publisher.objects.values_list().get(name = m_pk )
        fields_publisher = Publisher._meta.get_fields()[2:]
        mylist = zip(fields_publisher,d_publisher)
        context = {"state":"publisher","f_model":fields_publisher,"model_d":d_publisher,"mylist":mylist,"pk":m_pk}
    return render(request, 'books/edit.html',context)

@login_required
def query(request):
    if request.method == 'POST':
        db = MySQLdb.connect(host="mybookdatabase.mariadb.database.azure.com",    # your host, usually localhost
                            user="admin_mnk@mybookdatabase",         # your username
                            passwd="#Patt1994",  # your password
                            db="bookdb")        # name of the data base
        cur = db.cursor()
        try:
            test_sql=request.POST['sql_code']
            print(test_sql)
        except (KeyError):
            return render(request, 'books/query.html')
        else:
            try:
                cur.execute(test_sql)
            except:
                context = {'state':'qury', 'code':test_sql,'error':'Query not found'}
                return render(request, 'books/query.html',context)
            else:
                desc = cur.description
                query_list = cur.fetchall()
                print(query_list)
                context = {'state':'query', 'query': query_list,'code':test_sql,'len_query':len(query_list),'desc':desc}
                return render(request, 'books/query.html',context)
    return render(request, 'books/query.html', {'state': 'query'})

books/templates/books/author_list.html
{% extends "books/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% if user.is_authenticated %}
<div class="content-section">
  <legend class="border-bottom mb-4">
    <a
      data-toggle="collapse"
      href="#insertCollapse"
      role="button"
      aria-expanded="false"
      aria-controls="insertCollapse"
      >Insert data</a
    >
  </legend>
  <form
    method="POST"
    action={% url 'books:insert' state %}
    class="collapse multi-collapse"
    id="insertCollapse"
  >
    {% csrf_token %}
    <fieldset class="form-group">
      {{ form|crispy }}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-info" type="submit">Save</button>
    </div>
  </form>
</div>
{% endif %}
<div class="content-section">
  <legend class="border-bottom mb-4">Search</legend>
  <form action="{% url 'books:search-author' %}" method="post">
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="name">Author :</label>
        <input type="text" class="form-control" name="name" />
      </div>
      <div class="form-group col-md-2">
        <label>: </label>
        <input
          type="submit"
          class="form-control btn btn-primary"
          value="Search"
        />
      </div>
    </div>
  </form>
  <div class="table-responsive">
    <table class="table table-hover">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">Name</th>
          <th scope="col">Date of Birth</th>
          <th scope="col">Publisher</th>
          {% if user.is_authenticated %}
          <th scope="col">Extra Option</th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
        {% for author in authors %}
        <tr>
          <th scope="row">{{ forloop.counter0|add:authors.start_index }}</th>
          <td>{{ author.author_name}}</td>
          <td>{{ author.date_of_birth}}</td>
          <td>
            {% for i in author.works_for.all %}
            <ul>
              <li>{{i.name}}</li>
            </ul>
            {% endfor %}
          </td>
          {% if user.is_authenticated %}
          <td>
            <button type="button" class="btn btn-outline-primary btn-sm" onclick="location.href='{% url 'books:edit' state author.author_name %}'">E</button>
            <button type="button" class="btn btn-outline-danger btn-sm" onclick="location.href='{% url 'books:delete_data' state author.author_name %}'">D</button>
          </td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% if authors.has_other_pages %}

    {% if authors.has_previous %}
      <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
      <a class="btn btn-outline-info mb-4" href="?page={{ authors.previous_page_number }}">Previous</a>
    {% endif %}

    {% for num in authors.paginator.page_range %}
      {% if authors.number == num %}
        <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
      {% elif num > authors.number|add:'-3' and num < authors.number|add:'3' %}
        <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
      {% endif %}
    {% endfor %}

    {% if authors.has_next %}
      <a class="btn btn-outline-info mb-4" href="?page={{ authors.next_page_number }}">Next</a>
      <a class="btn btn-outline-info mb-4" href="?page={{ authors.paginator.num_pages }}">Last</a>
    {% endif %}

  {% endif %}
  </div>
</div>
{% endblock content %}

books/templates/books/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
    <style>
body {
    background: #fafafa;
    color: #333333;
    margin-top: 5rem;
  }
  
  h1, h2, h3, h4, h5, h6 {
    color: #444444;
  }
  
  ul {
    margin: 0;
  }
  
  .bg-steel {
    background-color: #061C23;
  }
  
  .site-header .navbar-nav .nav-link {
    color: #cbd5db;
  }
  
  .site-header .navbar-nav .nav-link:hover {
    color: #ffffff;
  }
  
  .site-header .navbar-nav .nav-link.active {
    font-weight: 500;
  }
  
  .content-section {
    background: #ffffff;
    padding: 10px 20px;
    border: 1px solid #dddddd;
    border-radius: 3px;
    margin-bottom: 20px;
  }
  
  .article-title {
    color: #444444;
  }
  
  a.article-title:hover {
    color: #428bca;
    text-decoration: none;
  }
  
  .article-content {
    white-space: pre-line;
  }
  
  .article-img {
    height: 65px;
    width: 65px;
    margin-right: 16px;
  }
  
  .article-metadata {
    padding-bottom: 1px;
    margin-bottom: 4px;
    border-bottom: 1px solid #e3e3e3
  }
  
  .article-metadata a:hover {
    color: #333;
    text-decoration: none;
  }
  
  .article-svg {
    width: 25px;
    height: 25px;
    vertical-align: middle;
  }
  
  .account-img {
    height: 125px;
    width: 125px;
    margin-right: 20px;
    margin-bottom: 16px;
  }
  
  .account-heading {
    font-size: 2.5rem;
  }
    </style>

    <link rel="stylesheet" type="text/css" href="{% static 'books/main.css' %}">

    <title>The Book DB</title>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'books:home' %}" style="color: #00D277">The Book DB</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <span class="navbar-brand mb-0 h2">{{ user.username }}</span>
                
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-3">
          <div class="content-section text-center">
            <h3 class="" style="font-weight: bold;">{{ state|title }}</h3>
            <p class='text-muted'>You can search any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light"><a href="{% url 'books:book' %}">Book</a></li>
                <li class="list-group-item list-group-item-light"><a href="{% url 'books:author' %}">Author</a></li>
                <li class="list-group-item list-group-item-light"><a href="{% url 'books:publisher' %}">Publisher</a></li>
                {% if user.is_authenticated %}
                  <li class="list-group-item list-group-item-light"><a href="{% url 'books:query' %}">Query</a></li>
                {% endif %}
              </ul>
            </p>
          </div>
        </div>
        <div class="col-md-9">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

books/templates/books/book_home.html
{% extends "books/base.html" %} {% block content %}
<div class="content-section text-center">
    <h2>Welcome to The Book DB</h2>
    <p>G.5</p>
    <img src="https://image.freepik.com/free-vector/people-outside-bookstore-vector_53876-17179.jpg" alt="">
</div>
{% endblock content %}

books/templates/books/book_list.html
{% extends "books/base.html" %} {% load crispy_forms_tags %} {% block content %}
{% if user.is_authenticated %}
<div class="content-section">
  <legend class="border-bottom mb-4">
    <a
      data-toggle="collapse"
      href="#insertCollapse"
      role="button"
      aria-expanded="false"
      aria-controls="insertCollapse"
      >Insert data</a
    >
  </legend>
  <form
    method="POST"
    action={% url 'books:insert' state %}
    class="collapse multi-collapse"
    id="insertCollapse"
  >
    {% csrf_token %}
    <fieldset class="form-group">
      {{ form|crispy }}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-info" type="submit">Save</button>
    </div>
  </form>
</div>
{% endif %}
<div class="content-section">
  <legend class="border-bottom mb-4">Search</legend>
    <form action= "{% url 'books:search-book' %}" method="post">
      {% csrf_token %}
      <div class="form-row">
      <div class="form-group col-md-4">
        <label for="name">Book :</label>
        <input type="search" class="form-control" name="book_name">
      </div>
      <div class="form-group col-md-4">
        <label for="name">Publisher :</label>
        <input type="search" class="form-control" name="publisher_name">
      </div>
      <div class="form-group col-md-2"> 
      <label for="year">Year :</label>
      <input type="search" class="form-control" name="year">
      </div> 
      <div class="form-group col-md-2">
      <label>: </label>
      <input type="submit" class="form-control btn btn-primary" value="Search">    
      </div>
      </div>    
    </form>
  <div class="table-responsive">
    <table class="table table-hover">
      <thead class="thead-dark">
        <tr>
          <th scope="col">#</th>
          <th scope="col">ISBN</th>
          <th scope="col">Title</th>
          <th scope="col">Published Date</th>
          <th scope="col">Publisher</th>
          <th scope="col">Author</th>
          {% if user.is_authenticated %}
            <th scope="col" width="15%">Extra Option</th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
        {% for book in books %}
        <tr>
          <th scope="row">{{ forloop.counter0|add:books.start_index }}</th>
          <td>{{ book.isbn}}</td>
          <td>{{ book.title}}</td>
          <td>{{ book.published_date}}</td>
          <td>{{ book.publisher}}</td>
          <td>
            {% for author in book.written.all%}
            <ul>
              <li>{{author.author_name}}</li>
            </ul>
            {% endfor %}
          </td>
              {% if user.is_authenticated %}
          <td>
            <button type="button" class="btn btn-outline-primary btn-sm" onclick="location.href='{% url 'books:edit' state book.isbn %}'">E</button>
            <button type="button" class="btn btn-outline-danger btn-sm" onclick="location.href='{% url 'books:delete_data' state book.isbn %}'">D</button>
          </td>
              {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
          {% if books.has_other_pages %}

      {% if books.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ books.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in books.paginator.page_range %}
        {% if books.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > books.number|add:'-3' and num < books.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if books.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ books.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ books.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
  </div>
</div>
{% endblock content %}

books/templates/books/publisher_list.html
{% extends "books/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{% if user.is_authenticated %}
<div class="content-section">
  <legend class="border-bottom mb-4">
    <a
      data-toggle="collapse"
      href="#insertCollapse"
      role="button"
      aria-expanded="false"
      aria-controls="insertCollapse"
      >Insert data</a
    >
  </legend>
  <form
    method="POST"
    action={% url 'books:insert' state %}
    class="collapse multi-collapse"
    id="insertCollapse"
  >
    {% csrf_token %}
    <fieldset class="form-group">
      {{ form|crispy }}
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-info" type="submit">Save</button>
    </div>
  </form>
</div>
{% endif %}
<div class="content-section">
  <legend class="border-bottom mb-4">Search</legend>
  <form action="{% url 'books:search-publisher' %}" method="post">
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="name">Publisher :</label>
        <input type="text" class="form-control" name="name" />
      </div>
      <div class="form-group col-md-2">
        <label>: </label>
        <input
          type="submit"
          class="form-control btn btn-primary"
          value="Search"
        />
      </div>
    </div>
  </form>
  <div class="table-responsive">
    <table class="table table-hover">
    <thead class="thead-dark">
        <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Adress</th>
        <th scope="col">Phone</th>
          {% if user.is_authenticated %}
          <th scope="col">Extra Option</th>
          {% endif %}
        </tr>
    </thead>
    <tbody>
        {% for publisher in publishers %}
        <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ publisher.name}}</td>
        <td>{{ publisher.address}}</td>
        <td>{{ publisher.phone}}</td>
          {% if user.is_authenticated %}
          <td>
            <button type="button" class="btn btn-outline-primary btn-sm" onclick="location.href='{% url 'books:edit' state publisher.name %}'">E</button>
            <button type="button" class="btn btn-outline-danger btn-sm" onclick="location.href='{% url 'books:delete_data' state publisher.name %}'">D</button>
          </td>
          {% endif %}
        </tr>
        {% endfor %}
    </tbody>
    </table>
    {% if publishers.has_other_pages %}

    {% if publishers.has_previous %}
      <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
      <a class="btn btn-outline-info mb-4" href="?page={{ publishers.previous_page_number }}">Previous</a>
    {% endif %}

    {% for num in publishers.paginator.page_range %}
      {% if publishers.number == num %}
        <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
      {% elif num > publishers.number|add:'-3' and num < publishers.number|add:'3' %}
        <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
      {% endif %}
    {% endfor %}

    {% if publishers.has_next %}
      <a class="btn btn-outline-info mb-4" href="?page={{ publishers.next_page_number }}">Next</a>
      <a class="btn btn-outline-info mb-4" href="?page={{ publishers.paginator.num_pages }}">Last</a>
    {% endif %}

  {% endif %}
  </div>
</div>
{% endblock content %}